import { useCallback, useEffect, useMemo, useState, Fragment } from 'react'
import { Printer, Banknote, RefreshCw, Truck, FileOutput, Layers, BadgeCheck, X } from 'lucide-react'
import { apiGet, apiPost } from '../lib/api'
import { formatMoney, formatDate, formatDateTime, formatAmountWords } from '../lib/format'
import { useToast } from '../components/ui/Toast'
import PageHeader from '../components/PageHeader'
import GlassCard from '../components/ui/GlassCard'
import StatusBadge from '../components/ui/StatusBadge'
import EmptyState from '../components/ui/EmptyState'
import Button from '../components/ui/Button'
import DataToolbar from '../components/ui/DataToolbar'
import ColumnsButton from '../components/ui/ColumnsButton'
import AdvancedFilter from '../components/ui/AdvancedFilter'
import GroupByPicker from '../components/ui/GroupByPicker'
import SummaryCards from '../components/ui/SummaryCards'
import SortableTh from '../components/ui/SortableTh'
import { downloadCSV, sortRows, dateSortValue, type SortDirection } from '../lib/export'
import { useColumnVisibility } from '../lib/columns'
import { applyFilters, type FilterColumnDef, type FilterLogic, type FilterState } from '../lib/filters'
import { groupRows } from '../lib/grouping'
import Modal from '../components/ui/Modal'
import { Field } from '../components/ui/Field'
import { useAuth, isFinanceOfficial } from '../lib/auth'
import { useFyLock } from '../lib/FyLockProvider'
import { emitCrossModule, useLiveDomain } from '../lib/store'
import { emitAppEvent } from '../lib/notify'
import {
  invoiceApprovedAmount,
  isAwaitingFinance,
  poGeneratedAmount,
  poReleasedAmount,
  poStatusLabel,
  poStatusTone,
} from '../lib/paymentOrder'

interface PaymentOrder {
  id: string
  serial_no: string | null
  generated_by: string | null
  generated_at: string | null
  status: string | null
  amount?: number | null
  approved_amount?: number | null
  released_amount?: number | null
  released_by?: string | null
  released_at?: string | null
  finance_approved_by?: string | null
  finance_approved_at?: string | null
  finance_remarks?: string | null
  invoices: {
    id?: string
    invoice_no: string | null
    invoice_date: string | null
    amount: number
    approved_amount?: number | null
    status: string | null
    cost_element?: string | null
    contracts: { contract_no: string | null; vendors: Array<{ name: string | null }> | null } | null
  } | null
}

const PO_COLUMN_KEYS = [
  'po_serial',
  'generated_at',
  'generated_by',
  'invoice_no',
  'invoice_date',
  'vendor',
  'contract',
  'amount',
  'approved_amount',
  'released_amount',
  'status',
]

const PO_DEFAULT_COLUMNS = ['po_serial', 'invoice_no', 'vendor', 'amount', 'released_amount', 'status']

const PO_COLUMN_LABELS: Record<string, string> = {
  po_serial: 'PO Serial',
  generated_at: 'Generated',
  generated_by: 'Generated By',
  invoice_no: 'Invoice',
  invoice_date: 'Invoice Date',
  vendor: 'Vendor',
  contract: 'Contract',
  amount: 'PO Amount',
  approved_amount: 'Invoice Approved',
  released_amount: 'Payment Released',
  status: 'Status',
}

const PO_FILTER_COLUMNS: FilterColumnDef[] = [
  { key: 'po_serial', label: 'PO Serial', type: 'text' },
  { key: 'invoice_no', label: 'Invoice', type: 'text' },
  { key: 'vendor', label: 'Vendor', type: 'text' },
  { key: 'contract', label: 'Contract', type: 'text' },
  { key: 'generated_by', label: 'Generated By', type: 'text' },
  { key: 'generated_at', label: 'Generated At', type: 'date' },
  { key: 'invoice_date', label: 'Invoice Date', type: 'date' },
  { key: 'amount', label: 'PO Amount', type: 'number' },
  { key: 'status', label: 'Status', type: 'text' },
]

export default function PaymentOrdersPage() {
  const [orders, setOrders] = useState<PaymentOrder[]>([])
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)
  const [search, setSearch] = useState('')
  const [sortBy, setSortBy] = useState('generated_at')
  const [sortDir, setSortDir] = useState<SortDirection>('desc')
  const onSort = (key: string, dir: SortDirection) => {
    setSortBy(key)
    setSortDir(dir)
  }
  const [filters, setFilters] = useState<FilterState[]>([])
  const [filterLogic, setFilterLogic] = useState<FilterLogic>('and')
  const [groupKey, setGroupKey] = useState<string | null>(null)
  const col = useColumnVisibility('prl-eoms-cols-payment-orders-v2', PO_COLUMN_KEYS, PO_DEFAULT_COLUMNS)
  const toast = useToast()
  const { user } = useAuth()
  const finance = isFinanceOfficial(user?.role)
  const { guardWrite } = useFyLock()
  const [clearing, setClearing] = useState<PaymentOrder | null>(null)
  const [rejecting, setRejecting] = useState<PaymentOrder | null>(null)
  const [releasedAmount, setReleasedAmount] = useState('')
  const [remarks, setRemarks] = useState('')
  const [rejectReason, setRejectReason] = useState('')
  const [busy, setBusy] = useState(false)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const d = await apiGet<{ paymentOrders: PaymentOrder[] }>('/api/payment-orders')
      setOrders(d.paymentOrders)
    } catch (e) {
      toast.error('Failed to load payment orders', (e as Error).message)
    } finally {
      setLoading(false)
    }
  }, [toast])

  useEffect(() => {
    load()
  }, [load])

  const [, liveVersion] = useLiveDomain(['paymentOrders'])
  useEffect(() => {
    if (liveVersion === 0) return
    void load()
  }, [liveVersion, load])

  const refresh = async () => {
    setRefreshing(true)
    await load()
    setRefreshing(false)
  }

  const vendorOf = (o: PaymentOrder) => o.invoices?.contracts?.vendors?.[0]?.name ?? '—'
  const contractOf = (o: PaymentOrder) => o.invoices?.contracts?.contract_no ?? '—'
  const approvedOf = (o: PaymentOrder) => invoiceApprovedAmount({ amount: o.invoices?.amount, approved_amount: o.approved_amount ?? o.invoices?.approved_amount })
  const generatedOf = (o: PaymentOrder) => poGeneratedAmount(o, o.invoices)
  const releasedOf = (o: PaymentOrder) => poReleasedAmount(o)

  const filtered = useMemo(() => {
    const q = search.toLowerCase()
    const searched = q
      ? orders.filter((o) =>
          `${o.serial_no ?? ''} ${o.invoices?.invoice_no ?? ''} ${vendorOf(o)} ${contractOf(o)}`.toLowerCase().includes(q),
        )
      : orders
    return applyFilters(searched, filters, PO_FILTER_COLUMNS, (o, key) => {
      if (key === 'vendor') return vendorOf(o)
      if (key === 'contract') return contractOf(o)
      if (key === 'invoice_no') return o.invoices?.invoice_no
      if (key === 'invoice_date') return o.invoices?.invoice_date
      if (key === 'amount') return generatedOf(o)
      if (key === 'po_serial') return o.serial_no
      return (o as unknown as Record<string, string | number | null>)[key] ?? null
    }, filterLogic)
  }, [orders, search, filters, filterLogic])

  const totalAmount = useMemo(
    () => filtered.reduce((s, o) => s + generatedOf(o), 0),
    [filtered],
  )
  const vendorCount = useMemo(() => new Set(filtered.map((o) => vendorOf(o))).size, [filtered])
  const awaitingCount = useMemo(() => filtered.filter((o) => isAwaitingFinance(o.status)).length, [filtered])
  const releasedTotal = useMemo(() => filtered.reduce((s, o) => s + releasedOf(o), 0), [filtered])

  const sorted = useMemo(
    () =>
      sortRows(
        filtered,
        sortBy || null,
        sortDir,
        (row, key) =>
          key === 'generated_at'
            ? dateSortValue(row.generated_at)
            : key === 'invoice_date'
              ? dateSortValue(row.invoices?.invoice_date)
              : key === 'amount'
                ? generatedOf(row)
                : key === 'vendor'
                  ? String(vendorOf(row))
                  : key === 'serial_no'
                    ? String(row.serial_no ?? '')
                    : key === 'contract'
                      ? String(contractOf(row))
                      : key === 'approved_amount'
                        ? approvedOf(row)
                        : key === 'released_amount'
                          ? releasedOf(row)
                          : key === 'generated_by'
                            ? String(row.generated_by ?? '')
                            : key === 'status'
                              ? String(row.status ?? '')
                              : String(row.invoices?.invoice_no ?? ''),
      ),
    [filtered, sortBy, sortDir],
  )

  const GROUP_BY_PO = [
    { key: 'vendor', label: 'Vendor' },
    { key: 'contract', label: 'Contract' },
    { key: 'month', label: 'Month of Invoice Date' },
    { key: 'status', label: 'Status' },
  ]

  const poGroupValue = (o: PaymentOrder, key: string): string | number | null => {
    if (key === 'vendor') return vendorOf(o)
    if (key === 'contract') return contractOf(o)
    if (key === 'month') return o.invoices?.invoice_date ? o.invoices.invoice_date.slice(0, 7) : null
    if (key === 'status') return poStatusLabel(o.status)
    return (o as unknown as Record<string, string | number | null>)[key] ?? null
  }

  const grouped = useMemo(
    () => groupRows(sorted, groupKey, poGroupValue, (o) => generatedOf(o)),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [sorted, groupKey],
  )

  const visibleColCount = PO_COLUMN_KEYS.filter((k) => col.show(k)).length + 1

  const exportCSV = () =>
    downloadCSV(
      `payment-orders-${new Date().toISOString().slice(0, 10)}.csv`,
      sorted.map((o) => ({
        ...(col.show('po_serial') ? { po_serial: o.serial_no ?? '' } : {}),
        ...(col.show('generated_at') ? { generated_at: o.generated_at ?? '' } : {}),
        ...(col.show('generated_by') ? { generated_by: o.generated_by ?? '' } : {}),
        ...(col.show('invoice_no') ? { invoice_no: o.invoices?.invoice_no ?? '' } : {}),
        ...(col.show('invoice_date') ? { invoice_date: o.invoices?.invoice_date ?? '' } : {}),
        ...(col.show('vendor') ? { vendor: vendorOf(o) } : {}),
        ...(col.show('contract') ? { contract: contractOf(o) } : {}),
        ...(col.show('approved_amount') ? { invoice_approved: approvedOf(o) } : {}),
        ...(col.show('amount') ? { po_amount: generatedOf(o) } : {}),
        ...(col.show('released_amount') ? { payment_released: releasedOf(o) } : {}),
        ...(col.show('status') ? { status: poStatusLabel(o.status) } : {}),
      })),
    )

  const print = (order: PaymentOrder) => {
    const inv = order.invoices
    const vendor = inv?.contracts?.vendors?.[0]?.name ?? '—'
    const contractNo = inv?.contracts?.contract_no ?? '—'
    const poAmt = generatedOf(order)
    const relAmt = releasedOf(order)
    const printAmt = relAmt > 0 ? relAmt : poAmt
    const logoUrl = `${window.location.origin}/brand/prl-logo.png`
    const win = window.open('', '_blank', 'width=800,height=900')
    if (!win) return
    win.document.write(`<!doctype html><html><head><title>PO ${order.serial_no}</title>
      <style>
        body{font-family:'Segoe UI',Arial,sans-serif;margin:48px;color:#111}
        .head{display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #1e3a8a;padding-bottom:16px}
        .brand{display:flex;align-items:center;gap:14px}
        .brand img{height:52px;width:auto}
        .head h1{margin:0;color:#1e3a8a;font-size:22px}
        .sub{font-size:12px;color:#555}
        .meta{margin:24px 0;display:flex;justify-content:space-between;font-size:14px}
        table{width:100%;border-collapse:collapse;margin-top:16px;font-size:13px}
        th,td{border:1px solid #ccc;padding:8px 10px;text-align:left}
        th{background:#f1f5f9}
        .amount{text-align:right}
        .words{margin-top:24px;font-size:13px;color:#333}
        .sign{margin-top:60px;display:flex;justify-content:space-between;font-size:13px}
        .sign .box{border-top:1px solid #333;padding-top:6px;width:200px;text-align:center}
      </style></head><body>
      <div class="head">
        <div class="brand">
          <img src="${logoUrl}" alt="PRL" />
          <div><h1>Pakistan Refinery Limited</h1><div class="sub">Payment Order / Cheque Request</div></div>
        </div>
        <div><strong>PO No:</strong> ${order.serial_no ?? ''}<br/><span class="sub">${formatDateTime(order.generated_at)}</span></div>
      </div>
      <div class="meta">
        <div><strong>Vendor:</strong> ${vendor}</div>
        <div><strong>Contract:</strong> ${contractNo}</div>
        <div><strong>Invoice:</strong> ${inv?.invoice_no ?? ''} (${formatDate(inv?.invoice_date)})</div>
      </div>
      <table>
        <tr><th>Description</th><th class="amount">Amount (PKR)</th></tr>
        <tr><td>Payment against invoice ${inv?.invoice_no ?? ''} — ${contractNo}</td><td class="amount"><strong>${formatMoney(printAmt, 2)}</strong></td></tr>
      </table>
      <div class="words">In words: <strong>${formatAmountWords(printAmt)}</strong></div>
      <div class="sign">
        <div class="box">Prepared By</div>
        <div class="box">Finance Official</div>
        <div class="box">Accounts</div>
      </div>
      <script>window.print()</script>
      </body></html>`)
    win.document.close()
  }

  const openClear = (o: PaymentOrder) => {
    setClearing(o)
    setReleasedAmount(String(generatedOf(o)))
    setRemarks(o.finance_remarks ?? '')
  }

  const submitClear = async () => {
    if (!clearing) return
    if (!(await guardWrite(clearing.invoices?.invoice_date))) return
    setBusy(true)
    try {
      await apiPost(`/api/payment-orders/${clearing.id}/approve`, {
        releasedAmount: Number(releasedAmount || generatedOf(clearing)),
        remarks: remarks.trim() || undefined,
      })
      toast.success('Payment released', `${clearing.serial_no} cleared; surveyor payment deducted from budget`)
      emitAppEvent('ok', 'Payment released', `PO ${clearing.serial_no} cleared by finance`, '/payment-orders')
      emitCrossModule('paymentOrder', 'update', clearing.id)
      setClearing(null)
      await load()
    } catch (e) {
      toast.error('Finance approval failed', (e as Error).message)
    } finally {
      setBusy(false)
    }
  }

  const submitReject = async () => {
    if (!rejecting) return
    if (!rejectReason.trim()) {
      toast.error('A rejection reason is required')
      return
    }
    if (!(await guardWrite(rejecting.invoices?.invoice_date))) return
    setBusy(true)
    try {
      await apiPost(`/api/payment-orders/${rejecting.id}/reject`, { reason: rejectReason.trim() })
      toast.success('Payment order rejected', rejecting.serial_no ?? '')
      emitAppEvent('err', 'PO rejected by finance', `${rejecting.serial_no} — ${rejectReason.trim()}`, '/payment-orders')
      emitCrossModule('paymentOrder', 'update', rejecting.id)
      setRejecting(null)
      setRejectReason('')
      await load()
    } catch (e) {
      toast.error('Finance reject failed', (e as Error).message)
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="space-y-5">
      <PageHeader
        title="Payment Orders"
        description="Finance takes the last decision: approve a pay order to release payment to the surveyor and deduct it from budget."
        actions={
          <>
            <Button variant="ghost" onClick={refresh} disabled={refreshing}>
              <RefreshCw size={15} className={refreshing ? 'animate-spin' : ''} /> Refresh
            </Button>
            <span className="badge badge-info">
              <Banknote size={13} /> {orders.length} issued
            </span>
          </>
        }
      />

      <SummaryCards
        items={[
          {
            label: 'PO Generated',
            value: `Rs ${formatMoney(totalAmount)}`,
            sub: `${filtered.length} payment order${filtered.length === 1 ? '' : 's'}`,
            icon: <Banknote size={16} />,
            tone: 'primary',
          },
          {
            label: 'Awaiting Finance',
            value: String(awaitingCount),
            sub: 'generated, not yet cleared',
            icon: <FileOutput size={16} />,
            tone: 'warn',
          },
          {
            label: 'Payment Released',
            value: `Rs ${formatMoney(releasedTotal)}`,
            sub: `${vendorCount} vendor${vendorCount === 1 ? '' : 's'} in view`,
            icon: <Truck size={16} />,
            tone: 'ok',
          },
        ]}
      />

      <DataToolbar
        search={{ value: search, onChange: setSearch, placeholder: 'Search PO, invoice, vendor…' }}
        filterBar={<AdvancedFilter columns={PO_FILTER_COLUMNS} filters={filters} onChange={setFilters} logic={filterLogic} onLogicChange={setFilterLogic} />}
        sort={{
          columns: [
            { key: 'generated_at', label: 'Generated' },
            { key: 'serial_no', label: 'PO serial' },
            { key: 'invoice_date', label: 'Invoice date' },
            { key: 'vendor', label: 'Vendor' },
            { key: 'amount', label: 'Amount' },
          ],
          value: sortBy,
          direction: sortDir,
          onValueChange: setSortBy,
          onDirectionChange: setSortDir,
        }}
        onExport={exportCSV}
        exportLabel="Export CSV"
        resultsCount={sorted.length}
      >
        <ColumnsButton
          columns={PO_COLUMN_KEYS.map((k) => ({ key: k, label: PO_COLUMN_LABELS[k] }))}
          isVisible={col.show}
          onToggle={col.toggle}
          onReset={col.reset}
          hiddenCount={col.hiddenCount}
        />
        <GroupByPicker options={GROUP_BY_PO} value={groupKey} onChange={setGroupKey} />
      </DataToolbar>

      <GlassCard className="overflow-hidden">
        <div className="table-scroll">
          <table className="data-table">
            <thead>
              <tr>
                {col.show('po_serial') && <SortableTh label="PO Serial" columnKey="serial_no" sortKey={sortBy} direction={sortDir} onSort={onSort} />}
                {col.show('generated_at') && <SortableTh label="Generated" columnKey="generated_at" sortKey={sortBy} direction={sortDir} onSort={onSort} preferDesc />}
                {col.show('generated_by') && <SortableTh label="Generated By" columnKey="generated_by" sortKey={sortBy} direction={sortDir} onSort={onSort} />}
                {col.show('invoice_no') && <SortableTh label="Invoice" columnKey="invoice_no" sortKey={sortBy} direction={sortDir} onSort={onSort} />}
                {col.show('invoice_date') && <SortableTh label="Invoice Date" columnKey="invoice_date" sortKey={sortBy} direction={sortDir} onSort={onSort} preferDesc />}
                {col.show('vendor') && <SortableTh label="Vendor" columnKey="vendor" sortKey={sortBy} direction={sortDir} onSort={onSort} />}
                {col.show('contract') && <SortableTh label="Contract" columnKey="contract" sortKey={sortBy} direction={sortDir} onSort={onSort} />}
                {col.show('approved_amount') && <SortableTh label="Invoice Approved" columnKey="approved_amount" sortKey={sortBy} direction={sortDir} onSort={onSort} preferDesc align="right" />}
                {col.show('amount') && <SortableTh label="PO Amount" columnKey="amount" sortKey={sortBy} direction={sortDir} onSort={onSort} preferDesc align="right" />}
                {col.show('released_amount') && <SortableTh label="Released" columnKey="released_amount" sortKey={sortBy} direction={sortDir} onSort={onSort} preferDesc align="right" />}
                {col.show('status') && <SortableTh label="Status" columnKey="status" sortKey={sortBy} direction={sortDir} onSort={onSort} />}
                <th className="col-actions">Actions</th>
              </tr>
            </thead>
            <tbody>
              {(() => {
                const renderRow = (o: PaymentOrder) => (
                  <tr key={o.id}>
                    {col.show('po_serial') && <td className="font-semibold">{o.serial_no ?? '—'}</td>}
                    {col.show('generated_at') && <td className="text-xs">{formatDateTime(o.generated_at)}</td>}
                    {col.show('generated_by') && <td className="text-xs">{o.generated_by ?? '—'}</td>}
                    {col.show('invoice_no') && <td>{o.invoices?.invoice_no ?? '—'}</td>}
                    {col.show('invoice_date') && <td>{formatDate(o.invoices?.invoice_date)}</td>}
                    {col.show('vendor') && <td className="max-w-[10rem] overflow-hidden text-ellipsis">{vendorOf(o)}</td>}
                    {col.show('contract') && <td className="text-xs">{contractOf(o)}</td>}
                    {col.show('approved_amount') && <td className="text-right tabular-nums">{formatMoney(approvedOf(o))}</td>}
                    {col.show('amount') && <td className="text-right font-semibold tabular-nums">{formatMoney(generatedOf(o))}</td>}
                    {col.show('released_amount') && (
                      <td className="text-right tabular-nums">
                        {releasedOf(o) > 0 ? formatMoney(releasedOf(o)) : '—'}
                      </td>
                    )}
                    {col.show('status') && (
                      <td>
                        <StatusBadge tone={poStatusTone(o.status)}>{poStatusLabel(o.status)}</StatusBadge>
                      </td>
                    )}
                    <td className="col-actions">
                      <div className="flex justify-end gap-1">
                        {finance && isAwaitingFinance(o.status) && (
                          <>
                            <Button variant="success" size="sm" className="btn-icon" title="Approve & Release" aria-label="Approve & Release" onClick={() => openClear(o)}>
                              <BadgeCheck size={14} />
                            </Button>
                            <Button variant="danger" size="sm" className="btn-icon" title="Reject" aria-label="Reject" onClick={() => { setRejecting(o); setRejectReason('') }}>
                              <X size={14} />
                            </Button>
                          </>
                        )}
                        <Button variant="ghost" size="sm" className="btn-icon" title="Print" aria-label="Print" onClick={() => print(o)}>
                          <Printer size={14} />
                        </Button>
                      </div>
                    </td>
                  </tr>
                )

                const rows = grouped
                  ? grouped.map((g) => (
                      <Fragment key={`grp-${g.key}`}>
                        <tr className="subtotal-row">
                          <td colSpan={visibleColCount}>
                            <div className="flex items-center justify-between gap-3">
                              <span className="flex items-center gap-2 font-semibold">
                                <Layers size={13} className="text-[var(--accent)]" />
                                {groupKey === 'month' && /^\d{4}-\d{2}$/.test(g.key)
                                  ? new Date(`${g.key}-01`).toLocaleDateString(undefined, { year: 'numeric', month: 'long' })
                                  : g.key}
                              </span>
                              <span className="text-xs text-[var(--text-muted)]">
                                {g.count} PO{g.count === 1 ? '' : 's'} ·{' '}
                                <b className="text-[var(--text)]">Rs {formatMoney(g.sum)}</b>
                              </span>
                            </div>
                          </td>
                        </tr>
                        {g.rows.map(renderRow)}
                      </Fragment>
                    ))
                  : sorted.map(renderRow)

                return (
                  <>
                    {rows}
                  </>
                )
              })()}
            </tbody>
          </table>
        </div>
        {sorted.length > 0 && (
          <div className="flex flex-wrap items-center justify-between gap-2 border-t border-[var(--table-border)] px-4 py-3">
            <span className="text-xs font-bold uppercase tracking-wider">Grand Total</span>
            <span className="text-xs">
              {sorted.length} PO{sorted.length === 1 ? '' : 's'} ·{' '}
              <b>Rs {formatMoney(totalAmount)}</b> generated ·{' '}
              <b>Rs {formatMoney(releasedTotal)}</b> released
            </span>
          </div>
        )}
        {!loading && sorted.length === 0 && (
          <EmptyState
            title={search ? 'No matching payment orders' : 'No payment orders yet'}
            description={
              search
                ? 'Try a different search.'
                : 'Approve an invoice to generate a payment order. Finance then clears it to release payment.'
            }
          />
        )}
      </GlassCard>

      <Modal
        open={!!clearing}
        onClose={() => setClearing(null)}
        title={`Approve & release ${clearing?.serial_no ?? ''}`}
        footer={
          <>
            <Button variant="ghost" onClick={() => setClearing(null)} disabled={busy}>Cancel</Button>
            <Button variant="success" onClick={submitClear} disabled={busy}>
              <BadgeCheck size={15} /> {busy ? 'Releasing…' : 'Approve & Release'}
            </Button>
          </>
        }
      >
        {clearing && (
          <div className="space-y-3 text-sm">
            <p className="text-[var(--text-dim)]">
              This is the last finance decision. Payment is released to the surveyor and the amount is deducted from remaining budget.
            </p>
            <div className="flex justify-between"><span className="text-[var(--text-muted)]">Invoice approved</span><b>Rs {formatMoney(approvedOf(clearing))}</b></div>
            <div className="flex justify-between"><span className="text-[var(--text-muted)]">PO generated</span><b>Rs {formatMoney(generatedOf(clearing))}</b></div>
            <Field label="Released amount (Rs)">
              <input className="input" inputMode="decimal" value={releasedAmount} onChange={(e) => setReleasedAmount(e.target.value)} />
            </Field>
            <Field label="Remarks (optional)">
              <textarea className="input" rows={3} value={remarks} onChange={(e) => setRemarks(e.target.value)} />
            </Field>
          </div>
        )}
      </Modal>

      <Modal
        open={!!rejecting}
        onClose={() => setRejecting(null)}
        title={`Reject ${rejecting?.serial_no ?? ''}`}
        footer={
          <>
            <Button variant="ghost" onClick={() => setRejecting(null)} disabled={busy}>Cancel</Button>
            <Button variant="danger" onClick={submitReject} disabled={busy}>
              <X size={15} /> {busy ? 'Rejecting…' : 'Reject PO'}
            </Button>
          </>
        }
      >
        <Field label="Reason">
          <textarea className="input" rows={3} value={rejectReason} onChange={(e) => setRejectReason(e.target.value)} placeholder="Why finance is rejecting this pay order" />
        </Field>
      </Modal>
    </div>
  )
}
