import { useCallback, useEffect, useMemo, useState, Fragment } from 'react'
import { Printer, Banknote, RefreshCw, Truck, FileOutput, Layers } from 'lucide-react'
import { apiGet } from '../lib/api'
import { formatMoney, formatDate, formatDateTime, formatAmountWords } from '../lib/format'
import { useToast } from '../components/ui/Toast'
import PageHeader from '../components/PageHeader'
import GlassCard from '../components/ui/GlassCard'
import StatusBadge from '../components/ui/StatusBadge'
import EmptyState from '../components/ui/EmptyState'
import Button from '../components/ui/Button'
import DataToolbar from '../components/ui/DataToolbar'
import ColumnsButton from '../components/ui/ColumnsButton'
import AdvancedFilter from '../components/ui/AdvancedFilter'
import GroupByPicker from '../components/ui/GroupByPicker'
import SummaryCards from '../components/ui/SummaryCards'
import { downloadCSV, sortRows, dateSortValue, type SortDirection } from '../lib/export'
import { useColumnVisibility } from '../lib/columns'
import { applyFilters, type FilterColumnDef, type FilterState } from '../lib/filters'
import { groupRows } from '../lib/grouping'

interface PaymentOrder {
  id: string
  serial_no: string | null
  generated_by: string | null
  generated_at: string | null
  status: string | null
  invoices: {
    invoice_no: string | null
    invoice_date: string | null
    amount: number
    status: string | null
    contracts: { contract_no: string | null; vendors: Array<{ name: string | null }> | null } | null
  } | null
}

const PO_COLUMN_KEYS = [
  'po_serial',
  'generated_at',
  'generated_by',
  'invoice_no',
  'invoice_date',
  'vendor',
  'contract',
  'amount',
  'status',
]

const PO_DEFAULT_COLUMNS = ['po_serial', 'generated_at', 'invoice_no', 'invoice_date', 'vendor', 'contract', 'amount', 'status']

const PO_COLUMN_LABELS: Record<string, string> = {
  po_serial: 'PO Serial',
  generated_at: 'Generated',
  generated_by: 'Generated By',
  invoice_no: 'Invoice',
  invoice_date: 'Invoice Date',
  vendor: 'Vendor',
  contract: 'Contract',
  amount: 'Amount',
  status: 'Status',
}

const PO_FILTER_COLUMNS: FilterColumnDef[] = [
  { key: 'po_serial', label: 'PO Serial', type: 'text' },
  { key: 'invoice_no', label: 'Invoice', type: 'text' },
  { key: 'vendor', label: 'Vendor', type: 'text' },
  { key: 'contract', label: 'Contract', type: 'text' },
  { key: 'generated_by', label: 'Generated By', type: 'text' },
  { key: 'generated_at', label: 'Generated At', type: 'date' },
  { key: 'invoice_date', label: 'Invoice Date', type: 'date' },
  { key: 'amount', label: 'Amount', type: 'number' },
]

export default function PaymentOrdersPage() {
  const [orders, setOrders] = useState<PaymentOrder[]>([])
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)
  const [search, setSearch] = useState('')
  const [sortBy, setSortBy] = useState('generated_at')
  const [sortDir, setSortDir] = useState<SortDirection>('desc')
  const [filters, setFilters] = useState<FilterState[]>([])
  const [groupKey, setGroupKey] = useState<string | null>(null)
  const col = useColumnVisibility('prl-eoms-cols-payment-orders', PO_COLUMN_KEYS, PO_DEFAULT_COLUMNS)
  const toast = useToast()

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const d = await apiGet<{ paymentOrders: PaymentOrder[] }>('/api/payment-orders')
      setOrders(d.paymentOrders)
    } catch (e) {
      toast.error('Failed to load payment orders', (e as Error).message)
    } finally {
      setLoading(false)
    }
  }, [toast])

  useEffect(() => {
    load()
  }, [load])

  const refresh = async () => {
    setRefreshing(true)
    await load()
    setRefreshing(false)
  }

  const vendorOf = (o: PaymentOrder) => o.invoices?.contracts?.vendors?.[0]?.name ?? '—'
  const contractOf = (o: PaymentOrder) => o.invoices?.contracts?.contract_no ?? '—'

  const filtered = useMemo(() => {
    const q = search.toLowerCase()
    const searched = q
      ? orders.filter((o) =>
          `${o.serial_no ?? ''} ${o.invoices?.invoice_no ?? ''} ${vendorOf(o)} ${contractOf(o)}`.toLowerCase().includes(q),
        )
      : orders
    return applyFilters(searched, filters, PO_FILTER_COLUMNS, (o, key) => {
      if (key === 'vendor') return vendorOf(o)
      if (key === 'contract') return contractOf(o)
      if (key === 'invoice_no') return o.invoices?.invoice_no
      if (key === 'invoice_date') return o.invoices?.invoice_date
      if (key === 'amount') return o.invoices?.amount
      return (o as unknown as Record<string, string | number | null>)[key] ?? null
    })
  }, [orders, search, filters])

  const totalAmount = useMemo(
    () => filtered.reduce((s, o) => s + Number(o.invoices?.amount ?? 0), 0),
    [filtered],
  )
  const vendorCount = useMemo(() => new Set(filtered.map((o) => vendorOf(o))).size, [filtered])

  const sorted = useMemo(
    () =>
      sortRows(
        filtered,
        sortBy || null,
        sortDir,
        (row, key) =>
          key === 'generated_at'
            ? dateSortValue(row.generated_at)
            : key === 'invoice_date'
              ? dateSortValue(row.invoices?.invoice_date)
              : key === 'amount'
                ? Number(row.invoices?.amount ?? 0)
                : key === 'vendor'
                  ? String(vendorOf(row))
                  : key === 'serial_no'
                    ? String(row.serial_no ?? '')
                    : String(row.invoices?.invoice_no ?? ''),
      ),
    [filtered, sortBy, sortDir],
  )

  const GROUP_BY_PO = [
    { key: 'vendor', label: 'Vendor' },
    { key: 'contract', label: 'Contract' },
    { key: 'month', label: 'Month of Invoice Date' },
  ]

  const poGroupValue = (o: PaymentOrder, key: string): string | number | null => {
    if (key === 'vendor') return vendorOf(o)
    if (key === 'contract') return contractOf(o)
    if (key === 'month') return o.invoices?.invoice_date ? o.invoices.invoice_date.slice(0, 7) : null
    return (o as unknown as Record<string, string | number | null>)[key] ?? null
  }

  const grouped = useMemo(
    () => groupRows(sorted, groupKey, poGroupValue, (o) => Number(o.invoices?.amount ?? 0)),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [sorted, groupKey],
  )

  const visibleColCount = PO_COLUMN_KEYS.filter((k) => col.show(k)).length + 1

  const exportCSV = () =>
    downloadCSV(
      `payment-orders-${new Date().toISOString().slice(0, 10)}.csv`,
      sorted.map((o) => ({
        ...(col.show('po_serial') ? { po_serial: o.serial_no ?? '' } : {}),
        ...(col.show('generated_at') ? { generated_at: o.generated_at ?? '' } : {}),
        ...(col.show('generated_by') ? { generated_by: o.generated_by ?? '' } : {}),
        ...(col.show('invoice_no') ? { invoice_no: o.invoices?.invoice_no ?? '' } : {}),
        ...(col.show('invoice_date') ? { invoice_date: o.invoices?.invoice_date ?? '' } : {}),
        ...(col.show('vendor') ? { vendor: vendorOf(o) } : {}),
        ...(col.show('contract') ? { contract: contractOf(o) } : {}),
        ...(col.show('amount') ? { amount: o.invoices?.amount ?? 0 } : {}),
        ...(col.show('status') ? { status: o.status ?? '' } : {}),
      })),
    )

  const print = (order: PaymentOrder) => {
    const inv = order.invoices
    const vendor = inv?.contracts?.vendors?.[0]?.name ?? '—'
    const contractNo = inv?.contracts?.contract_no ?? '—'
    const logoUrl = `${window.location.origin}/brand/prl-logo.png`
    const win = window.open('', '_blank', 'width=800,height=900')
    if (!win) return
    win.document.write(`<!doctype html><html><head><title>PO ${order.serial_no}</title>
      <style>
        body{font-family:'Segoe UI',Arial,sans-serif;margin:48px;color:#111}
        .head{display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #1e3a8a;padding-bottom:16px}
        .brand{display:flex;align-items:center;gap:14px}
        .brand img{height:52px;width:auto}
        .head h1{margin:0;color:#1e3a8a;font-size:22px}
        .sub{font-size:12px;color:#555}
        .meta{margin:24px 0;display:flex;justify-content:space-between;font-size:14px}
        table{width:100%;border-collapse:collapse;margin-top:16px;font-size:13px}
        th,td{border:1px solid #ccc;padding:8px 10px;text-align:left}
        th{background:#f1f5f9}
        .amount{text-align:right}
        .words{margin-top:24px;font-size:13px;color:#333}
        .sign{margin-top:60px;display:flex;justify-content:space-between;font-size:13px}
        .sign .box{border-top:1px solid #333;padding-top:6px;width:200px;text-align:center}
      </style></head><body>
      <div class="head">
        <div class="brand">
          <img src="${logoUrl}" alt="PRL" />
          <div><h1>Pakistan Refinery Limited</h1><div class="sub">Payment Order / Cheque Request</div></div>
        </div>
        <div><strong>PO No:</strong> ${order.serial_no ?? ''}<br/><span class="sub">${formatDateTime(order.generated_at)}</span></div>
      </div>
      <div class="meta">
        <div><strong>Vendor:</strong> ${vendor}</div>
        <div><strong>Contract:</strong> ${contractNo}</div>
        <div><strong>Invoice:</strong> ${inv?.invoice_no ?? ''} (${formatDate(inv?.invoice_date)})</div>
      </div>
      <table>
        <tr><th>Description</th><th class="amount">Amount (PKR)</th></tr>
        <tr><td>Payment against invoice ${inv?.invoice_no ?? ''} — ${contractNo}</td><td class="amount"><strong>${formatMoney(inv?.amount ?? 0, 2)}</strong></td></tr>
      </table>
      <div class="words">In words: <strong>${formatAmountWords(inv?.amount ?? 0)}</strong></div>
      <div class="sign">
        <div class="box">Prepared By</div>
        <div class="box">Approved By</div>
        <div class="box">Accounts</div>
      </div>
      <script>window.print()</script>
      </body></html>`)
    win.document.close()
  }

  return (
    <div className="space-y-5">
      <PageHeader
        title="Payment Orders"
        description="Generated payment orders for approved invoices."
        actions={
          <>
            <Button variant="ghost" onClick={refresh} disabled={refreshing}>
              <RefreshCw size={15} className={refreshing ? 'animate-spin' : ''} /> Refresh
            </Button>
            <span className="badge badge-info">
              <Banknote size={13} /> {orders.length} issued
            </span>
          </>
        }
      />

      <SummaryCards
        items={[
          {
            label: 'Total Issued',
            value: `Rs ${formatMoney(totalAmount)}`,
            sub: `${filtered.length} payment order${filtered.length === 1 ? '' : 's'}`,
            icon: <Banknote size={16} />,
            tone: 'primary',
          },
          {
            label: 'Vendors Paid',
            value: String(vendorCount),
            sub: 'distinct vendors',
            icon: <Truck size={16} />,
            tone: 'purple',
          },
          {
            label: 'Generated',
            value: String(filtered.length),
            sub: 'in current view',
            icon: <FileOutput size={16} />,
            tone: 'ok',
          },
        ]}
      />

      <DataToolbar
        search={{ value: search, onChange: setSearch, placeholder: 'Search PO, invoice, vendor…' }}
        filterBar={<AdvancedFilter columns={PO_FILTER_COLUMNS} filters={filters} onChange={setFilters} />}
        sort={{
          columns: [
            { key: 'generated_at', label: 'Generated' },
            { key: 'serial_no', label: 'PO serial' },
            { key: 'invoice_date', label: 'Invoice date' },
            { key: 'vendor', label: 'Vendor' },
            { key: 'amount', label: 'Amount' },
          ],
          value: sortBy,
          direction: sortDir,
          onValueChange: setSortBy,
          onDirectionChange: setSortDir,
        }}
        onExport={exportCSV}
        exportLabel="Export CSV"
        resultsCount={sorted.length}
      >
        <ColumnsButton
          columns={PO_COLUMN_KEYS.map((k) => ({ key: k, label: PO_COLUMN_LABELS[k] }))}
          isVisible={col.show}
          onToggle={col.toggle}
          onReset={col.reset}
          hiddenCount={col.hiddenCount}
        />
        <GroupByPicker options={GROUP_BY_PO} value={groupKey} onChange={setGroupKey} />
      </DataToolbar>

      <GlassCard className="overflow-hidden">
        <div className="overflow-x-auto">
          <table className="data-table">
            <thead>
              <tr>
                {col.show('po_serial') && <th>PO Serial</th>}
                {col.show('generated_at') && <th>Generated</th>}
                {col.show('generated_by') && <th>Generated By</th>}
                {col.show('invoice_no') && <th>Invoice</th>}
                {col.show('invoice_date') && <th>Invoice Date</th>}
                {col.show('vendor') && <th>Vendor</th>}
                {col.show('contract') && <th>Contract</th>}
                {col.show('amount') && <th className="text-right">Amount</th>}
                {col.show('status') && <th>Status</th>}
                <th className="text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {(() => {
                const renderRow = (o: PaymentOrder) => (
                  <tr key={o.id}>
                    {col.show('po_serial') && <td className="font-semibold">{o.serial_no ?? '—'}</td>}
                    {col.show('generated_at') && <td className="text-xs">{formatDateTime(o.generated_at)}</td>}
                    {col.show('generated_by') && <td className="text-xs">{o.generated_by ?? '—'}</td>}
                    {col.show('invoice_no') && <td>{o.invoices?.invoice_no ?? '—'}</td>}
                    {col.show('invoice_date') && <td>{formatDate(o.invoices?.invoice_date)}</td>}
                    {col.show('vendor') && <td>{vendorOf(o)}</td>}
                    {col.show('contract') && <td className="text-xs">{contractOf(o)}</td>}
                    {col.show('amount') && <td className="text-right font-semibold">{formatMoney(o.invoices?.amount ?? 0)}</td>}
                    {col.show('status') && <td><StatusBadge tone="ok">{o.status ?? 'Generated'}</StatusBadge></td>}
                    <td>
                      <div className="flex justify-end">
                        <Button variant="ghost" size="sm" onClick={() => print(o)}>
                          <Printer size={14} /> Print
                        </Button>
                      </div>
                    </td>
                  </tr>
                )

                const rows = grouped
                  ? grouped.map((g) => (
                      <Fragment key={`grp-${g.key}`}>
                        <tr className="subtotal-row">
                          <td colSpan={visibleColCount}>
                            <div className="flex items-center justify-between gap-3">
                              <span className="flex items-center gap-2 font-semibold">
                                <Layers size={13} className="text-[var(--accent)]" />
                                {groupKey === 'month' && /^\d{4}-\d{2}$/.test(g.key)
                                  ? new Date(`${g.key}-01`).toLocaleDateString(undefined, { year: 'numeric', month: 'long' })
                                  : g.key}
                              </span>
                              <span className="text-xs text-[var(--text-muted)]">
                                {g.count} PO{g.count === 1 ? '' : 's'} ·{' '}
                                <b className="text-[var(--text)]">Rs {formatMoney(g.sum)}</b>
                              </span>
                            </div>
                          </td>
                        </tr>
                        {g.rows.map(renderRow)}
                      </Fragment>
                    ))
                  : sorted.map(renderRow)

                return (
                  <>
                    {rows}
                    {sorted.length > 0 && (
                      <tr className="grand-total-row">
                        <td colSpan={visibleColCount}>
                          <div className="flex items-center justify-between gap-3">
                            <span className="font-bold uppercase tracking-wider">Grand Total</span>
                            <span className="text-xs">
                              {sorted.length} PO{sorted.length === 1 ? '' : 's'} ·{' '}
                              <b>Rs {formatMoney(totalAmount)}</b>
                            </span>
                          </div>
                        </td>
                      </tr>
                    )}
                  </>
                )
              })()}
            </tbody>
          </table>
        </div>
        {!loading && sorted.length === 0 && (
          <EmptyState
            title={search ? 'No matching payment orders' : 'No payment orders yet'}
            description={
              search
                ? 'Try a different search.'
                : 'Approve an invoice and generate a payment order from the Invoices page.'
            }
          />
        )}
      </GlassCard>
    </div>
  )
}
